from django.urls import path,re_path
from .import views
from django.contrib.auth import views as auth_view
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings 
from django.conf import settings
"""<a href="{% url 'update' slug=instance.slug %}"> Edit </a>
<a href="{% url 'delete' slug=instance.slug %}"> Delete</a> """
urlpatterns = [
    # path("ip",views.get_client_ip),
    path('',views.home,name="home"),
    path("logout", views.logout_request, name="logout"),
    path("dashboard",views.dashboard),
    path('index',views.indextable1),
    path('index2',views.indextable2),
    path("profile",views.profilee,name="profile"),
    path("about-us",views.aboutus,name="aboutus"),
    path("contact-us",views.contactuss,name="contactus"),
    path("city",views.cityy,name="city"),
    path("faqs",views.faqs,name="faq"),
    path("newsletter",views.newsletter,name="newsletter"),
    path("search",views.search,name="search"),
    path("coupon",views.coupon,name="coupon"),
    path("category",views.categoryy,name="category"),
    path("userinfo",views.userinfo,name="userinfo"),
    path("upload-prescription",views.prescriptionbookview,name="prescription-upload"),
    path("othersdetail",views.othersdetail,name="othersdetail"),
    path("prescriptionbreak",views.prescriptionbreak,name="prescriptionbreak"),
    path("lab-tests",views.testselect,name="testselect"),
    path('delete', views.destroy,name="destroy"),
    path('razorclose',views.razorpayclose,name="razorpayclose"),
    path("cart",views.cartt,name="cart"),
    path("addtocart",views.addtocart,name="addtocart"),
    path("addtocartt",views.addtocart1,name="addtocartt"),
    path("healthcheckupadd",views.healthcheckupadd,name="healthcheckupadd"),
    path("booking-history",views.BookingHistoryPay.as_view(),name="booking-history"),
    path("invoice/<str:orderid>",views.invoice,name="invoice"),
    path('health-checkup',views.healthcheckupview, name='Health-checkup'),
    path("packages",views.hpackagess,name="packages"),
    path('health-checkups',views.healthcheckupallview, name='Health-checkups'),
    path('health-packages/<slug:slug>',views.healthpackageview, name='Health-package'),
    path('life-style-assessments/<slug:slug>',views.healthsymptomview, name='Health-symptoms'),
    path('blog-details/<slug:slug>',views.healthcareblogsview, name='blogsdetail'),
    path('blog-categories/<slug:slug>',views.categoryblog, name='categoryblog'),
    path('registration',views.Registration, name="Registration"),
    path('registration/otp/',views.otpRegistration, name="otp-Registration"),
    path('resend',views.resendotp,name="resend"),
    path("book-test-online",views.booktestonline,name="bookonline"),
    path("changepassword",views.changepassword,name="changepassword"),
    path('forgotpassword',views.forgotpassword,name="forgot-password"),
    path("forgotpassword/otp/",views.otpforgotpassword,name="otp-forgotpassword"),
    path('login/',views.userLogin, name="user-login"),
    path("forgotresend",views.resendotpforgot,name="resendotpforgot"),
    path("changeresend",views.changeresend,name="changeresend"),
    path("changepasswordotp/",views.changepasswordotp,name="changepasswordotp"),
    path("passwordcheck",views.passwordcheck,name="passwordcheck"),
    path("testdetails",views.testdetails,name="testdetails"),
    path("privacy-policy",views.privacypolicy,name="privacy-policy"),
    path("payment-refund",views.paymentsrefund,name="payment-refund"),
    path("terms-of-use",views.termsofuse,name="termsofuse"),
    # path('login/otp/',views.otpLogin, name="otp-login"),
    # path('logout/',auth_view.LogoutView.as_view(template_name='logout.html')),
    # path('email-verify/', views.email_verification, name="email-verify"),
    # path('forget-password/',views.forget_password,name="forger-password"),
    # path('forget-password/done/',TemplateView.as_view(template_name='forget-password-done.html')),
    # path('change-password/<slug:uid>/',views.change_password,name="change-password"),
    path('paymenthandler/<str:str>/<str:amount>/', views.paymenthandler, name='paymenthandler'),
    path("cartsessiondelete",views.cartsessiondelete,name="cartsessiondelete"),
    path("requestcall",views.requestcallheader,name="requestcall"),
    path("lifestyle-assessments/<slug:slug>/",views.HealthSymptoms.as_view(),name="health_symptoms"),
    path("couponsessiondelete",views.couponsessiondelete,name='couponsessiondelete'),
    path("csv",views.uploadcsv,name="csv"),
    path("lifestyletests",views.lifestyletests,name="lifestyletests"),
    path('lifestyle-assessments',views.lifestyleassessment,name="lifestyles"),
    path('readfile',views.readfile,name="readfile"),
    path('medicationpost',views.medicationsview,name="medicationpost"),
    path('medicationdelete',views.medicationdelete,name="medicationdelete"),
    path('medicationinfo',views.medicationinfo,name="medicationinfo"),
    path('medicupdate',views.medicupdate,name="medicupdate"),
    path("franchisee-opportunities",views.franchise,name="franchise"),
    path("our-centers",views.ourcenters,name="ourcenters"),
    path("career",views.career,name="career"),
    path("send-report/<str:phone>/<str:bookingid>/",views.sendreport,name="sendreport"),
    path("report",views.reportotp,name="reportotp"),
    path("adminemail",views.erroremailadmin,name="erroradminemail"),
    path("savedd",views.dummyy),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

