# Generated by Django 4.0.5 on 2022-09-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutspan',
            options={'verbose_name': 'About Span', 'verbose_name_plural': 'About Span'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blogs Category', 'verbose_name_plural': 'Blogs Category'},
        ),
        migrations.AlterModelOptions(
            name='book_history',
            options={'verbose_name': 'Booking Histories', 'verbose_name_plural': 'Booking Histories'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Test Category', 'verbose_name_plural': 'Test Category'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact us form', 'verbose_name_plural': 'Contact us form'},
        ),
        migrations.AlterModelOptions(
            name='couponredeem',
            options={'verbose_name': 'Redeemed Coupons', 'verbose_name_plural': 'Redeemed Coupons'},
        ),
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'Coupons', 'verbose_name_plural': 'Coupons'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQ'},
        ),
        migrations.AlterModelOptions(
            name='healthcareblogs',
            options={'verbose_name': 'Blogs', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckuppackages',
            options={'verbose_name': 'Popular Tests', 'verbose_name_plural': 'Popular Tests'},
        ),
        migrations.AlterModelOptions(
            name='healthpackages',
            options={'verbose_name': 'Health Packages', 'verbose_name_plural': 'Health Packages'},
        ),
        migrations.AlterModelOptions(
            name='healthsymptoms',
            options={'verbose_name': 'Life Style Assesments', 'verbose_name_plural': 'Life Style Assesments'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payments History', 'verbose_name_plural': 'Payments History'},
        ),
        migrations.AlterModelOptions(
            name='prescriptionbook1',
            options={'verbose_name': 'Prescription Bookings', 'verbose_name_plural': 'Prescription Bookings'},
        ),
        migrations.AlterModelOptions(
            name='requestcall',
            options={'verbose_name': 'Call Back Requests', 'verbose_name_plural': 'Call Back Requests'},
        ),
        migrations.AlterModelOptions(
            name='socialmedialinks',
            options={'verbose_name': 'Social media links', 'verbose_name_plural': 'Social media links'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Master Test', 'verbose_name_plural': 'Tests'},
        ),
        migrations.AlterModelOptions(
            name='testbook',
            options={'verbose_name': 'Test Bookings', 'verbose_name_plural': 'Test Bookings'},
        ),
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'Testimonials', 'verbose_name_plural': 'Testimonials'},
        ),
        migrations.AddField(
            model_name='invoicee',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='invoice', verbose_name='Invoice File'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='cityy',
            field=models.ManyToManyField(blank=True, to='app1.city', verbose_name='City'),
        ),
    ]
