# Generated by Django 4.0.5 on 2022-07-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_history',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book_history',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book_history',
            name='status',
            field=models.CharField(choices=[('p', 'On Process'), ('u', 'updated'), ('t', 'tested')], default='', max_length=8, null=True),
        ),
    ]
