# Generated by Django 4.0.5 on 2022-07-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Payment Ids',
            },
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Payments History'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='dob',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='healthcheckuppackages',
            name='dpricel5',
        ),
        migrations.RemoveField(
            model_name='healthcheckuppackages',
            name='dpricel6',
        ),
        migrations.RemoveField(
            model_name='healthcheckuppackages',
            name='pricel5',
        ),
        migrations.RemoveField(
            model_name='healthcheckuppackages',
            name='pricel6',
        ),
        migrations.AddField(
            model_name='cart',
            name='labtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.healthcheckuppackages'),
        ),
        migrations.AddField(
            model_name='cart',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.healthpackages'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dpricel2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chennai Discounted Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dpricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mumbai DiscountedPrice'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dpricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delhi Discounted Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='pricel2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chennai Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='pricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mumbai Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='pricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delhi Price'),
        ),
    ]
