# Generated by Django 4.0.5 on 2022-07-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthsymptoms',
            name='bengaluru_price',
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='Banglore_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Banglore Price'),
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='Mumbai_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mumbai Price'),
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='aurangabad_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Aurangabad Price'),
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='barshi_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Barshi Price'),
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='bhopal_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bhopal Price'),
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='nanded_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Nanded Price'),
        ),
        migrations.AddField(
            model_name='healthsymptoms',
            name='pune_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pune Price'),
        ),
    ]
