# Generated by Django 4.0.5 on 2022-07-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_healthsymptoms_bengaluru_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_history',
            name='bookingid',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Booking Id'),
        ),
    ]
