# Generated by Django 4.0.5 on 2022-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_paymentids_alter_payment_options_rename_dob_user_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Device'),
        ),
    ]
