# Generated by Django 4.0.5 on 2022-09-06 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_aboutspan_options_alter_blogcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicee',
            options={'verbose_name': 'Invoice', 'verbose_name_plural': 'Invoice'},
        ),
    ]
