# Generated by Django 4.0.5 on 2022-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_cart_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsymptoms',
            name='bengaluru_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
