# Generated by Django 4.0.5 on 2022-07-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_book_history_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
