# Generated by Django 4.0.5 on 2022-07-28 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_book_history_bookingid'),
    ]

    operations = [
        migrations.CreateModel(
            name='couponredeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('coupon', models.CharField(blank=True, max_length=200, null=True)),
                ('discountpercen', models.CharField(blank=True, max_length=200, null=True, verbose_name='Discount(%)')),
                ('discountamount', models.CharField(blank=True, max_length=20, null=True, verbose_name='Discounted Price(₹)')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualamount', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'Redeemed Coupons',
            },
        ),
        migrations.CreateModel(
            name='invoicee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('healthsymptoms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.healthsymptoms', verbose_name='Health Symptoms')),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptionbook1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.CharField(blank=True, max_length=20, null=True)),
                ('unique', models.UUIDField(blank=True, null=True)),
                ('prescription_file', models.FileField(blank=True, null=True, upload_to='prescription')),
                ('myself', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('others_choice', models.CharField(blank=True, choices=[('m', 'Mother'), ('f', 'Father'), ('w', 'Wife'), ('s', 'Son'), ('d', 'Daughter'), ('o', 'Other')], default='', max_length=8, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default='', max_length=8, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='report')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prescription Bookings',
            },
        ),
        migrations.CreateModel(
            name='testbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingid', models.CharField(blank=True, max_length=20, null=True)),
                ('unique', models.UUIDField(blank=True, null=True)),
                ('tests', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('myself', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('others_choice', models.CharField(blank=True, choices=[('m', 'Mother'), ('f', 'Father'), ('w', 'Wife'), ('s', 'Son'), ('d', 'Daughter'), ('o', 'Other')], default='', max_length=8, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default='', max_length=8, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('report', models.FileField(blank=True, null=True, upload_to='report')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Test Bookings',
            },
        ),
        migrations.RemoveField(
            model_name='cart2',
            name='items',
        ),
        migrations.RemoveField(
            model_name='cart2',
            name='user',
        ),
        migrations.DeleteModel(
            name='paymentids',
        ),
        migrations.AlterModelOptions(
            name='healthcheckuppackages',
            options={'verbose_name_plural': 'Health Checkups and Lab Tests'},
        ),
        migrations.AlterModelOptions(
            name='prescription_book',
            options={'verbose_name_plural': 'Prescription Bookings1'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Registered Users'},
        ),
        migrations.AddField(
            model_name='book_history',
            name='uni',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='prescription_book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='testcode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Test Code'),
        ),
        migrations.AlterField(
            model_name='book_history',
            name='amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='book_history',
            name='bookingid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=16, max_length=40, null=True, prefix='DP', verbose_name='Booking Id'),
        ),
        migrations.AlterField(
            model_name='book_history',
            name='payment_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentid',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Payment Id'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transid',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Order Id'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'female'), ('o', 'others')], default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=13, null=True, unique=True, verbose_name='Mobile number'),
        ),
        migrations.DeleteModel(
            name='cart2',
        ),
        migrations.AddField(
            model_name='testbook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionbook1',
            name='test_name',
            field=models.ManyToManyField(blank=True, to='app1.test'),
        ),
        migrations.AddField(
            model_name='prescriptionbook1',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicee',
            name='items',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.test'),
        ),
        migrations.AddField(
            model_name='invoicee',
            name='labtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.healthcheckuppackages'),
        ),
        migrations.AddField(
            model_name='invoicee',
            name='packages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.healthpackages'),
        ),
        migrations.AddField(
            model_name='invoicee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
