# Generated by Django 4.0.5 on 2022-08-16 04:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_couponredeem_invoicee_prescriptionbook1_testbook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheckuppackages',
            options={'verbose_name_plural': 'Popular Tests'},
        ),
        migrations.AlterModelOptions(
            name='healthsymptoms',
            options={'verbose_name_plural': 'Life Style Assesments'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dBanglore_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Banglore Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Discount(%)'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='package_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Test Name'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='test_name',
            field=models.ManyToManyField(blank=True, to='app1.test'),
        ),
        migrations.AlterField(
            model_name='healthpackages',
            name='test_name',
            field=models.ManyToManyField(blank=True, to='app1.test'),
        ),
        migrations.AlterField(
            model_name='healthsymptoms',
            name='test_name',
            field=models.ManyToManyField(blank=True, to='app1.test'),
        ),
        migrations.CreateModel(
            name='requestcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='First Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('tests', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.test')),
            ],
            options={
                'verbose_name_plural': 'Call Back Requests',
            },
        ),
    ]
