# Generated by Django 4.0.5 on 2022-07-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_test_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='prescription_book',
        ),
        migrations.AlterModelOptions(
            name='prescription_book',
            options={'verbose_name_plural': 'Prescription Booking'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='app1.test'),
        ),
        migrations.AlterField(
            model_name='cart2',
            name='items',
            field=models.ManyToManyField(to='app1.test'),
        ),
    ]
