# Generated by Django 4.0.5 on 2022-07-17 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_healthsymptoms_bengaluru_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='healthsymptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.healthsymptoms', verbose_name='Health Symptoms'),
        ),
    ]
