# Generated by Django 4.0.5 on 2022-08-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_couponredeem_invoicee_prescriptionbook1_testbook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestcall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(blank=True, max_length=100, null=True, verbose_name='First Name')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='First Name')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('tests', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.test')),
            ],
        ),
    ]
