# Generated by Django 4.0.5 on 2022-09-06 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_subscription_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='careers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phoneno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone No')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('cv', models.FileField(blank=True, null=True, upload_to='careerCV')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Careers Form',
            },
        ),
        migrations.CreateModel(
            name='careersopenings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designations', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designations')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Career Designations',
            },
        ),
        migrations.CreateModel(
            name='franchisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Full Name')),
                ('phoneno', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone No')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('taluka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Taluka')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Franchise',
            },
        ),
        migrations.CreateModel(
            name='medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medic', models.TextField(blank=True, null=True, verbose_name='Medicine Name')),
                ('morning', models.BooleanField(default=True)),
                ('afternoon', models.BooleanField(default=True)),
                ('evening', models.BooleanField(default=True)),
                ('night', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Medications',
            },
        ),
    ]
