# Generated by Django 4.0.5 on 2022-07-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_rename_book_prescription_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription_book',
            name='test_name',
        ),
    ]
