# Generated by Django 4.0.5 on 2022-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_requestcall'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestcall',
            options={'verbose_name_plural': 'Call Back Requests'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactus',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcall',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcall',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
