# Generated by Django 4.0.5 on 2022-09-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_careers_careersopenings_franchisee_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionbook1',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='testbook',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='categoryy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.category'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='healthsymptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.healthsymptoms', verbose_name='Health Symptoms'),
        ),
        migrations.AlterField(
            model_name='invoicee',
            name='healthsymptoms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.healthsymptoms', verbose_name='Health Symptoms'),
        ),
        migrations.AlterField(
            model_name='prescriptionbook1',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='<small style="color:red">*Coupon Should be Apply Only Once"</small>', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.coupons'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.city', verbose_name='Locations'),
        ),
    ]
