# Generated by Django 4.0.5 on 2022-08-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_requestcall_options_contactus_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheckuppackages',
            options={'verbose_name_plural': 'Popular Tests'},
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='package_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Test Name'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='test_name',
            field=models.ManyToManyField(blank=True, to='app1.test'),
        ),
    ]
