# Generated by Django 4.0.5 on 2022-07-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_city_city_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='dpricel5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pune Discounted Price'),
        ),
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='dpricel6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='barshi Discounted Price'),
        ),
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='dpricel7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='aurangabad Discounted Price'),
        ),
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='pricel5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pune Price'),
        ),
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='pricel6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='barshi Price'),
        ),
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='pricel7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='aurangabad Price'),
        ),
        migrations.AddField(
            model_name='healthpackages',
            name='pricel7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='aurangabad Price'),
        ),
        migrations.AddField(
            model_name='test',
            name='pricel7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='aurangabad Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dpricel2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='bhopal Discounted Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dpricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nanded Discounted Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='pricel2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mumbai Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='pricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='bhopal Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='pricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nanded Price'),
        ),
        migrations.AlterField(
            model_name='healthpackages',
            name='pricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='bhopal Price'),
        ),
        migrations.AlterField(
            model_name='healthpackages',
            name='pricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nanded Price'),
        ),
        migrations.AlterField(
            model_name='healthpackages',
            name='pricel5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pune Price'),
        ),
        migrations.AlterField(
            model_name='healthpackages',
            name='pricel6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='barshi Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='bhopal Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='nanded Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='pune Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='barshi Price'),
        ),
    ]
