# Generated by Django 4.0.5 on 2022-07-02 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_prescription_book_test_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription_book',
            options={'verbose_name_plural': 'Prescription Bookings'},
        ),
        migrations.CreateModel(
            name='selectedtest_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myself', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('others_choice', models.CharField(choices=[('m', 'Mother'), ('f', 'Father'), ('s', 'Son'), ('d', 'Daughter'), ('o', 'Other')], default='', max_length=8, null=True)),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('age', models.CharField(blank=True, max_length=3, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=8, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('test_name', models.ManyToManyField(to='app1.test')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Test Bookings',
            },
        ),
    ]
