# Generated by Django 4.0.5 on 2022-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_prescription_book_options_selectedtest_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_book',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='selectedtest_book',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=8, null=True),
        ),
    ]
