# Generated by Django 4.0.5 on 2022-08-03 11:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_healthpackages_test_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='dBanglore_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Banglore Price'),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)], verbose_name='Discount(%)'),
        ),
    ]
