# Generated by Django 4.0.5 on 2022-07-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_city_city_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_icon',
            field=models.ImageField(blank=True, null=True, upload_to='photos/icons/'),
        ),
    ]
