# Generated by Django 4.0.5 on 2022-07-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_prescription_book_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_book',
            name='others_choice',
            field=models.CharField(blank=True, choices=[('m', 'Mother'), ('f', 'Father'), ('s', 'Son'), ('d', 'Daughter'), ('o', 'Other')], default='', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='selectedtest_book',
            name='others_choice',
            field=models.CharField(blank=True, choices=[('m', 'Mother'), ('f', 'Father'), ('s', 'Son'), ('d', 'Daughter'), ('o', 'Other')], default='', max_length=8, null=True),
        ),
    ]
