# Generated by Django 4.0.5 on 2022-07-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_prescription_book_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription_book',
            name='prescription_file',
            field=models.FileField(blank=True, null=True, upload_to='prescription'),
        ),
    ]
