# Generated by Django 4.0.5 on 2022-07-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_prescription_book_prescription_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_history',
            name='patient_info',
        ),
        migrations.AlterField(
            model_name='book_history',
            name='status',
            field=models.CharField(choices=[('p', 'On Process'), ('u', 'updated'), ('t', 'tested')], default='p', max_length=8, null=True),
        ),
    ]
