# Generated by Django 4.0.5 on 2022-07-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_book_history_patient_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_history',
            name='patient_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
