# Generated by Django 4.0.5 on 2022-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_book_history_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription_book',
            options={'verbose_name_plural': 'Test Bookings'},
        ),
        migrations.AlterModelOptions(
            name='selectedtest_book',
            options={'verbose_name_plural': 'Tests Bookings'},
        ),
        migrations.AddField(
            model_name='prescription_book',
            name='test_name',
            field=models.ManyToManyField(blank=True, null=True, to='app1.test'),
        ),
    ]
