# Generated by Django 4.0.5 on 2022-07-04 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_prescription_book_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='selectedtest_book',
        ),
    ]
