# Generated by Django 4.0.5 on 2022-07-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_delete_selectedtest_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmedialinks',
            name='twitter',
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socialmedialinks',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcheckuppackages',
            name='package_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Package Title'),
        ),
    ]
