# Generated by Django 4.0.5 on 2022-07-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_socialmedialinks_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Coupon Code')),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Coupons',
            },
        ),
    ]
