# Generated by Django 4.0.5 on 2022-07-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_coupons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthcheckuppackages',
            options={'verbose_name_plural': ' Health Checkup'},
        ),
        migrations.AlterField(
            model_name='coupons',
            name='discount',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Discount(%)'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='startdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start Date'),
        ),
    ]
