# Generated by Django 4.0.5 on 2022-07-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_healthcheckuppackages_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutspan',
            name='description2',
        ),
    ]
