# Generated by Django 4.0.5 on 2022-07-04 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_remove_aboutspan_description2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_history',
            options={'verbose_name_plural': 'Booking Histories'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='categoryy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.category'),
        ),
        migrations.AlterField(
            model_name='prescription_book',
            name='test_name',
            field=models.ManyToManyField(blank=True, to='app1.test'),
        ),
    ]
