# Generated by Django 4.0.5 on 2022-07-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_remove_cart_items_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Blogs Category',
            },
        ),
        migrations.AlterModelOptions(
            name='healthcareblogs',
            options={'verbose_name_plural': 'Blogs'},
        ),
    ]
