# Generated by Django 4.0.5 on 2022-07-05 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_healthcareblogs_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Test Category'},
        ),
        migrations.AlterModelOptions(
            name='healthcheckuppackages',
            options={'verbose_name_plural': 'Health Checkup'},
        ),
        migrations.AlterModelOptions(
            name='healthpackages',
            options={'verbose_name_plural': 'Health Packages'},
        ),
        migrations.AlterModelOptions(
            name='healthsymptoms',
            options={'verbose_name_plural': 'Health Symptoms'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name_plural': 'Tests'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='test',
            name='slug',
        ),
    ]
