# Generated by Django 4.0.5 on 2022-07-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_remove_healthcheckuppackages_test_nos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_history',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.prescription_book'),
        ),
    ]
