# Generated by Django 4.0.5 on 2022-07-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_book_history_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_history',
            name='test1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
