# Generated by Django 4.0.5 on 2022-07-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_book_history_test1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_history',
            name='test',
        ),
        migrations.RemoveField(
            model_name='book_history',
            name='test1',
        ),
        migrations.AddField(
            model_name='prescription_book',
            name='unique',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
