# Generated by Django 4.0.5 on 2022-07-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_remove_book_history_test_remove_book_history_test1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_history',
            name='testbooking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
