# Generated by Django 4.0.5 on 2022-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_remove_user_otp_user_address_user_dob_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthpackages',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Mobile number'),
        ),
    ]
