# Generated by Django 4.0.5 on 2022-07-06 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_healthpackages_description_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='testt',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Test'),
        ),
        migrations.CreateModel(
            name='pricee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.city')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.test')),
            ],
        ),
    ]
