# Generated by Django 4.0.5 on 2022-07-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_test_testt_pricee'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricee',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
