# Generated by Django 4.0.5 on 2022-07-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_pricee_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricee',
            options={'verbose_name_plural': 'Test Price'},
        ),
        migrations.RenameField(
            model_name='pricee',
            old_name='test',
            new_name='testt',
        ),
        migrations.AddField(
            model_name='test',
            name='amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.pricee'),
        ),
    ]
