# Generated by Django 4.0.5 on 2022-07-06 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_alter_pricee_options_rename_test_pricee_testt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='coupons',
            name='startdate',
        ),
        migrations.AddField(
            model_name='coupons',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pricee',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='pricee',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='pricee',
            name='testt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.test', verbose_name='Test'),
        ),
    ]
