# Generated by Django 4.0.5 on 2022-07-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_remove_coupons_enddate_remove_coupons_startdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active?'),
        ),
    ]
