# Generated by Django 4.0.5 on 2022-07-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_remove_healthpackages_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='amount',
        ),
    ]
