# Generated by Django 4.0.5 on 2022-07-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0041_remove_test_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='pricel1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='L1 Price'),
        ),
        migrations.AddField(
            model_name='test',
            name='pricel2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='L2 Price'),
        ),
        migrations.AddField(
            model_name='test',
            name='pricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='L3 Price'),
        ),
        migrations.AddField(
            model_name='test',
            name='pricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='L4 Price'),
        ),
        migrations.AddField(
            model_name='test',
            name='pricel5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='L5 Price'),
        ),
        migrations.AddField(
            model_name='test',
            name='pricel6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='L6 Price'),
        ),
    ]
