# Generated by Django 4.0.5 on 2022-07-06 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_test_pricel1_test_pricel2_test_pricel3_test_pricel4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='price',
        ),
    ]
