# Generated by Django 4.0.5 on 2022-07-06 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_healthsymptoms_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcheckuppackages',
            name='loaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.city', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='healthpackages',
            name='loaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.city', verbose_name='Location'),
        ),
    ]
