# Generated by Django 4.0.5 on 2022-07-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_healthcheckuppackages_loaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcheckuppackages',
            old_name='loaction',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='healthpackages',
            old_name='loaction',
            new_name='location',
        ),
    ]
