# Generated by Django 4.0.5 on 2022-07-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0046_rename_loaction_healthcheckuppackages_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription_book',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Banglore Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mumbai Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Chennai Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Hyderabad Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Delhi Price'),
        ),
        migrations.AlterField(
            model_name='test',
            name='pricel6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Kolkata Price'),
        ),
    ]
