# Generated by Django 4.0.5 on 2022-07-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0047_prescription_book_location_alter_test_pricel1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckuppackages',
            name='location',
        ),
        migrations.RemoveField(
            model_name='healthpackages',
            name='location',
        ),
    ]
