# Generated by Django 4.0.5 on 2022-07-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_remove_healthcheckuppackages_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcheckuppackages',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='healthpackages',
            name='slug',
        ),
    ]
