# Generated by Django 4.0.5 on 2022-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_black', '0002_alter_adminblacksetting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminblacksetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
